# Generated by Django 3.2.13 on 2022-10-17 14:48
from django.contrib.auth import get_user_model
from django.db import migrations

from dataworkspace.apps.core.utils import update_user_tool_access_policy


def migrate_team_members(apps, _):
    """
    Loop through users with team membership and update their
    s3 perms to allow for team prefixes
    """
    user_ids = apps.get_model("core", "TeamMembership").objects.values("user_id").distinct()
    users = get_user_model().objects.filter(id__in=user_ids)
    for user in users:
        update_user_tool_access_policy(user, user.profile.home_directory_efs_access_point_id)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_mlflowauthoriseduser_mlflowinstance"),
    ]

    operations = [
        migrations.RunPython(migrate_team_members, migrations.RunPython.noop),
    ]
